### ISSUE TITLE
[refactoring]: Move from deprecated ui.addStyle api to `ui.add_css`, `ui.add_scss` or `ui.add_sass`

### ISSUE THREAD

**Issue by ihsanKisi** [codecentric-oss/niceml-dashboard#12]
### ✏️ Problem Description

The ui.add_style is deprecated and the use of the api should be updated to `ui.add_css`, `ui.add_scss` or `ui.add_sass`.

### 💡 Feature Request

Please see above.

### 👍 Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aiakide** [comment]
Closes by #13
