### ISSUE TITLE
[Refactor]: Change buttons.py to sidebar_toggle_button.py

### ISSUE THREAD

**Issue by ihsanKisi** [codecentric-oss/niceml-dashboard#15]
### ✏️ Problem Description

The current name is confusing.

### 💡 Feature Request

Change the name to SidebarToggleButton

### 👍 Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aiakide** [comment]
Ok, I got the point. 
I would suggest creating a module called `buttons` that contains multiple button implementations. 
The fully qualified name of the sidebar button would be something like `nicemldashboard.basecomponents.buttons.SidebarToggleButton`.

**Comment by ihsanKisi** [comment]
Hi. Thanks that sounds good. I will update it accordingly.

**Comment by aiakide** [comment]
Solved by #18
