### ISSUE TITLE
[Feature]: Add Experiment Details View UI

### ISSUE THREAD

**Issue by ihsanKisi** [codecentric-oss/niceml-dashboard#19]
### ✏️ Problem Description

We are missing a panel, where the user can view the details of an experiment.

### 💡 Feature Request

We need the UI that provides the structure for the experiment details view. For the starters, this UI should provide two tabs: Meta (can also be called the overview tab) and metrics. The meta tab will give an overview of a single experiment and the metrics tab will provide graphs that describe metrics such as accuracy over the epocs etc. The implementation should be kept as generic as possible to later on support comparisons between multiple experiments, as well as custom tabs. 

### 🔍 Additional Information

This figma sketch can give an idea of how it should look.
<img width="822" alt="image" src="https://github.com/codecentric-oss/niceml-dashboard/assets/114022183/15f57d7f-6cfc-4df3-bab7-a69d395d7181">

### 👍 Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ihsanKisi** [comment]
I just found a design from TensorOpera AI that I think will be useful for our design. 
<img width="1327" alt="image" src="https://github.com/codecentric-oss/niceml-dashboard/assets/114022183/cd7f25a7-f999-4ffd-8f93-e61aa42eaf20">

**Comment by aiakide** [comment]
The experiment detail view should be a separate page and work with a parameter that is the experiment ID (dashboard.local/detail-view?experiment-id=as234234 or dashboard.local/detail-view/as234234).

**Comment by aiakide** [comment]
The tabs that are displayed in the detailed view must be loaded dynamically based on a configuration. These components all inherit from an abstract class. Each component must decide whether it should be rendered in the current state of the dashboard. For example not every component is suitable for every experiment type. The classes can look like this:

**Comment by aiakide** [comment]
```mermaid
classDiagram
    class ExperimentDetailComponent{
        + str: name
        - StateManager _state_manager
        
        - _should_be_rendered*()
    }
    <<Abstract>> ExperimentDetailComponent
    class CustomExperimentDetailViewComponet{
        + str: name
        - StateManager _state_manager
        + _should_be_rendered()
    }
    CustomExperimentDetailViewComponet <|-- ExperimentDetailComponent
```
