### ISSUE TITLE
[Bug]: Python 3.9 support is not working

### ISSUE THREAD

**Issue by ihsanKisi** [codecentric-oss/niceml-dashboard#6]
### ✏️ Problem Description

The dashboard does not start because the inspect.get_annotations function in experiment.py is only available starting with python version 3.10, as can be seen in the screenshot below. I do not have the error log anymore but the issue can be reproduced by using python 3.9.16.

### 💡 Feature Request

Either the support should be added for python 3.9 or the dependency should be updated to 3.10

### 🔍 Additional Information

<img width="478" alt="image" src="https://github.com/codecentric-oss/niceml-dashboard/assets/114022183/5c2a580c-bebc-4d16-9680-ef1772085a2a">

### 👍 Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aiakide** [comment]
Closes by #13
